#!/bin/bash

yum update && yum upgrade
yum install -y mc nano
yum install -y net-tools
yum install epel-release -y
yum install pptpd.x86_64 -y

rm -f /etc/sysctl.conf
cat >>/etc/sysctl.conf<<EOF
net.ipv4.ip_forward = 1
EOF

rm -f /etc/pptpd.conf
cat >>/etc/pptpd.conf<<EOF
option /etc/ppp/options.pptpd
logwtmp
localip 10.0.0.1
remoteip 10.0.0.100-200
EOF

rm -f /etc/ppp/options.pptpd
cat >>/etc/ppp/options.pptpd<<EOF
name pptpd
refuse-pap
refuse-chap
refuse-mschap
require-mschap-v2
#require-mppe-128
proxyarp
lock
nobsdcomp.
novj
novjccomp
nologfd
ms-dns 8.8.8.8
ms-dns 8.8.4.4
EOF

rm -f /etc/ppp/chap-secrets
cat >>/etc/ppp/chap-secrets<<EOF
vpnuser pptpd vu321Fi *
EOF

sysctl -p

rm -f /etc/ppp/ip-up
cat >>/etc/ppp/ip-up<<EOF
#!/bin/bash
# This file should not be modified -- make local changes to
# /etc/ppp/ip-up.local instead
PATH=/sbin:/usr/sbin:/bin:/usr/bin
export PATH
LOGDEVICE=$6
REALDEVICE=$1
[ -f /etc/sysconfig/network-scripts/ifcfg-${LOGDEVICE} ] && /etc/sysconfig/network-scripts/ifup-post --realdevice
/etc/ppp/ip-up.ipv6to4 ${LOGDEVICE}
[ -x /etc/ppp/ip-up.local ] && /etc/ppp/ip-up.local "$@"
/sbin/ifconfig $1 mtu 1420
exit 0
EOF

service pptpd restart

systemctl stop firewalld
systemctl mask firewalld
yum install iptables-services -y
systemctl enable iptables

rm -f /etc/sysconfig/iptables
cat >>/etc/sysconfig/iptables<<EOF
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A POSTROUTING -o eth0 -j MASQUERADE
COMMIT
# Generated by iptables-save v1.4.21 on Fri Nov 13 02:12:55 2015
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [853:222169]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
#-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -i eth0 -p tcp -m tcp --dport 1723 -j ACCEPT
-A INPUT -i eth0 -p gre -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A INPUT -p gre -j ACCEPT
-A INPUT -p tcp -m tcp --dport 1723 -j ACCEPT
-A FORWARD -i ppp+ -o eth0 -j ACCEPT
-A FORWARD -i eth0 -o ppp+ -j ACCEPT
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT
EOF

systemctl restart iptables
